### ISSUE TITLE
How to get rid of this top bar?

### ISSUE THREAD

**Issue by chaaaeeee** [stav121/i3wm-themer#147]
i want to get rid of this top bar, i don't know how.

is it the polybar? i have uninstalled polybar with pacman -Rns polybar and  already deleted its config directory (~/.config/polybar) but it is still there? is it not the polybar? or have i done something wrong? i use ./install_arch.sh to install i3wm-themer btw

can someone help?

![2024-03-15-14:31:04-screenshot](https://github.com/stav121/i3wm-themer/assets/138379828/ed0ad353-0a23-4e6f-a818-255df6607e11)

**Comment by chaaaeeee** [comment]
lmao i just realized that i have to reboot in order for it to take effect

**Comment by stav121** [comment]
Hello @chaaaeeee , sorry for the late response. Yes rebooting or just refreshing i3 should work.
