### ISSUE TITLE
Apply theme colors to terminal?

### ISSUE THREAD

**Issue by aayc** [stav121/i3wm-themer#65]
Installation from script on Ubuntu 18.04 with i3 went great!  The only issue I ran into is that the terminal theme and color didn't seem to be applied to my terminal (i.e. it's still purple).  To install, I installed the Python dependencies, then ran the install script.  Is there a step I'm missing?

Thanks for your help :) these themes look amazing.

**Comment by unix121** [comment]
Hello sir! Are you using Gnome Terminal? If yes then you should change the default color values "by hand". Different terminal emulators have different configuration methods sadly and this is one of my goals for the next big update. Provide more configs for more terminal emulators.

But, in any case, if you switch to RxvtUnicode then you should not have this issue anymore :)
